# Based on
# - https://blog.jannikwempe.com/github-actions-trunk-based-development#heading-a-brief-introduction-to-trunk-based-development
# - https://blog.derlin.ch/github-actions-reusable-workflow-docker-images

name: Deploy G9 by pushing docker image

on:
  workflow_call:
    inputs:
      docker-image:
        description: "Required input to set docker image name"
        required: true
        type: string
      environment:
        description: "Required input to set environment"
        required: true
        type: string
      runs-on:
        description: "Optional input to set an operating systems which the workflow uses. Defaults to ubuntu-latest if not set"
        required: false
        type: string
        default: "ubuntu-latest"
      docker-context:
        description: "Optional input to set docker context"
        required: false
        type: string
        default: "."
      build-args:
        description: "Optional input to set docker build-time variables"
        required: false
        type: string
        default: ""
      docker-platforms:
        description: "Optional input list to set docker target platforms for build. Defaults to linux/amd64"
        required: false
        type: string
        default: "linux/amd64"
      timeout-minutes:
        description: "Optional input to set timeout minutes. Defaults to 15"
        required: false
        type: number
        default: 15

jobs:
  docker-trigger-deploy:
    name: Deploy by pushing docker image and triggering deploy workflow
    runs-on: ${{inputs.runs-on}}
    environment: ${{inputs.environment}}
    timeout-minutes: ${{inputs.timeout-minutes}}
    concurrency:
      group: deploy-${{inputs.environment}}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: environment
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ inputs.environment }}

      - name: Generate version
        id: version
        run: echo "version=${version}" >> "$GITHUB_OUTPUT"
        env:
          version: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}

      - name: Generate repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"

      - name: Build, tag and push Docker image
        id: docker
        uses: vmvt-devhub/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          push: true
          docker-image: ${{inputs.docker-image}}
          registry-password: ${{secrets.GITHUB_TOKEN}}
          environment: ${{inputs.environment}}
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
            ENVIRONMENT=${{ steps.environment.outputs.lowercase }}
            ${{inputs.build-args}}
          docker-context: ${{inputs.docker-context}}
          docker-platforms: ${{inputs.docker-platforms}}